# Matrisler

In [1]:
#Örnek-1
Matris_1 = matrix(c(7,3,4,3,5,2))
Matris_1

     [,1]
[1,] 7
[2,] 3
[3,] 4
[4,] 3
[5,] 5
[6,] 2

In [3]:
#Örnek-2, nrow parametresi ile satır sayısının 3 olduğu belirtiliyor
Matris_2 = matrix(c(7,3,4,3,5,2),nrow=3)
Matris_2

     [,1] [,2]
[1,] 7    3
[2,] 3    5
[3,] 4    2

In [4]:
#Örnek-2, ncol parametresi ile sütun sayısının 3 olduğu belirtiliyor
Matris_3 = matrix(c(7,3,4,3,5,2),ncol=3)
Matris_3

     [,1] [,2] [,3]
[1,] 7    4    5
[2,] 3    3    2

In [ ]:
Sutun_1 = c(1,2,3,4,5,6) 
Sutun_2 = c(7,8,9,10,11,12) 
Sutun_3 = c(13,14,15,16,17,18)
Matris_8 = as.matrix(cbind(Sutun_1,Sutun_2,Sutun_3))
Matris_8

     Sutun_1 Sutun_2 Sutun_3
[1,] 1        7      13
[2,] 2        8      14
[3,] 3        9      15
[4,] 4       10      16
[5,] 5       11      17
[6,] 6       12      18

In [6]:
L2_1=c(1,2,3,4,5,6,7,8,9,0)
L2_2=c("Kırmızı","Beyaz","Bordo","Mavi")
L2_3=c("Ayşe","Fatma","Hayriye")

L2=list(Numara=L2_1,Renk=L2_2,İsim=L2_3)


L2$Numara

 [1] 1 2 3 4 5 6 7 8 9 0

# Veri Çerçeveleri

In [7]:
VC_1 = data.frame (
  İsimler = c("ali", "ayşe", "fatma", "mehmet"),
  Boy = c(177,165,158,190),
  Yaş = c(25,27,19,41)
)

VC_1

  İsimler Boy Yaş
1 ali     177 25
2 ayşe    165 27
3 fatma   158 19
4 mehmet  190 41

In [8]:
VC_1[["Boy"]]

[1] 177 165 158 190

In [9]:
VC_1[c(2,3),] # 2. ve 3. satırlar.

  İsimler Boy Yaş
2 ayşe    165 27
3 fatma   158 19

In [10]:
attributes(VC_1) #satır isimlerini ya da numaralarını verir.

$names
[1] "İsimler" "Boy"     "Yaş"

$class
[1] "data.frame"

$row.names
[1] 1 2 3 4

In [11]:
nrow(VC_1) #satır sayısını verir.

[1] 4

In [12]:
 ncol(VC_1) #sütun sayısını verir.

[1] 3

In [13]:
colnames(VC_1) = c("Adı", "Boyu", "Yaşı")  #sütun isimleri
  attributes(VC_1)$names

[1] "Adı"  "Boyu" "Yaşı"

In [14]:
rownames(VC_1) = paste(seq(1,nrow(VC_1)),". Aday", sep = "")

In [15]:
show(VC_1)

           Adı Boyu Yaşı
1. Aday    ali  177   25
2. Aday   ayşe  165   27
3. Aday  fatma  158   19
4. Aday mehmet  190   41

#Bir veri çerçevesine sütun eklemek için cbind fonksiyonu kullanılır.

In [16]:
Kilo = c(75,65,57,80)
  VC_1=cbind(VC_1,Kilo)
  VC_1

        Adı    Boyu Yaşı Kilo
1. Aday ali    177  25   75
2. Aday ayşe   165  27   65
3. Aday fatma  158  19   57
4. Aday mehmet 190  41   80

Bir veri çerçevesinde araya sütun eklemek istersek de aşağıdaki şekilde yapabiliriz.

In [17]:
#araya sütun ekeleme
  Soyad = c("yilmaz", "türkmen", "aydin", "keskin")
  VC_1=data.frame(VC_1[,1:1],Soyad,VC_1[,2:4])
  colnames(VC_1) = c("Ad", "Soyad", "Boy", "Yaş", "Kilo") 
  VC_1

        Ad     Soyad   Boy Yaş Kilo
1. Aday ali    yilmaz  177 25  75
2. Aday ayşe   türkmen 165 27  65
3. Aday fatma  aydin   158 19  57
4. Aday mehmet keskin  190 41  80

Bir veri çerçevesine satır eklemek için rbind fonksiyonu kullanılır.

In [18]:
  yeni_satir=c("ahmet", "aksoy", "184","29","79")
  VC_1=rbind(VC_1,yeni_satir) 
  rownames(VC_1) = paste(seq(1,nrow(VC_1)),". Aday", sep = "") #satır isimleri
  VC_1

        Ad     Soyad   Boy Yaş Kilo
1. Aday ali    yilmaz  177 25  75
2. Aday ayşe   türkmen 165 27  65
3. Aday fatma  aydin   158 19  57
4. Aday mehmet keskin  190 41  80
5. Aday ahmet  aksoy   184 29  79

Veri çerçevelerinin birleştirilmesi için merge fonksiyonu kullanılır. Bu işlem yapılırken birleştirilen veri çerçeveleri arasında ismi ve içeriği bakımından ortak bir ya da birden çok sütun bulunmaldır. Aksi takdirde birleştirme işlemi sonucunda çalışma mantığı gereği satır sayısı artacaktır.

In [19]:
VC_2 = data.frame (
  isim = c("ali", "ayşe", "fatma", "mehmet"), #ortak isim ve içerikli sütun
  boy = c(177,165,158,190),
  yas = c(25,27,19,41)
)

VC_3 = data.frame (
  isim = c("ali", "ayşe", "fatma", "mehmet"), #ortak isim ve içerikli sütun
  memleket = c("Trabzon","Uşak","Konya","Ankara"),
  meslek = c("Öğretmen","Doktor","Öğrenci","Müzisyen")
)

Birlestirilmis_VC_1 =  merge(VC_2,VC_3)
Birlestirilmis_VC_1

  isim   boy yas memleket meslek
1 ali    177 25  Trabzon  Öğretmen
2 ayşe   165 27  Uşak     Doktor
3 fatma  158 19  Konya    Öğrenci
4 mehmet 190 41  Ankara   Müzisyen

Aşağıdaki örnekte ortak isim ve içerikli herhangi bir sütun bulunmadığından birleştirme işlemi sonucu daha fazla satır sayısına sahip yeni bir veri çerçevesi oluşur. Oluşan yeni veri çerçevesinin satır sayısı birleşen veeri çerçevelerinin satır sayılarının çarpımı kadardır.

In [20]:
VC_4 = data.frame (
  isim = c("ali", "ayşe", "fatma", "mehmet"),
  boy = c(177,165,158,190),
  yas = c(25,27,19,41)
)

VC_5 = data.frame (

  memleket = c("Trabzon","Uşak","Konya","Ankara"),
  meslek = c("Öğretmen","Doktor","Öğrenci","Müzisyen")
)

Birlestirilmis_VC_2 =  merge(VC_4,VC_5)
Birlestirilmis_VC_2

   isim   boy yas memleket meslek
1  ali    177 25  Trabzon  Öğretmen
2  ayşe   165 27  Trabzon  Öğretmen
3  fatma  158 19  Trabzon  Öğretmen
4  mehmet 190 41  Trabzon  Öğretmen
5  ali    177 25  Uşak     Doktor
6  ayşe   165 27  Uşak     Doktor
7  fatma  158 19  Uşak     Doktor
8  mehmet 190 41  Uşak     Doktor
9  ali    177 25  Konya    Öğrenci
10 ayşe   165 27  Konya    Öğrenci
11 fatma  158 19  Konya    Öğrenci
12 mehmet 190 41  Konya    Öğrenci
13 ali    177 25  Ankara   Müzisyen
14 ayşe   165 27  Ankara   Müzisyen
15 fatma  158 19  Ankara   Müzisyen
16 mehmet 190 41  Ankara   Müzisyen

Veri çerçevelerinde satır ve sütun silme işlemi aşağıdaki gibi gerçekleştirilir.

In [21]:
Silinecek_VC_1 = VC_1 #VC_1 isimli veri çerçevesinin içeriğini Silinecek_VC_1 isimli veri çerçevesine aktardık.

#veri çerçevesinin ilk hali
Silinecek_VC_1

        Ad     Soyad   Boy Yaş Kilo
1. Aday ali    yilmaz  177 25  75
2. Aday ayşe   türkmen 165 27  65
3. Aday fatma  aydin   158 19  57
4. Aday mehmet keskin  190 41  80
5. Aday ahmet  aksoy   184 29  79

In [22]:
#Sütun silme işlemi için aşağıdaki yöntemleri kullanılabilir.
Silinecek_VC_1[,-3] #Yöntem 1, 3.sütun siliniyor.

        Ad     Soyad   Yaş Kilo
1. Aday ali    yilmaz  25  75
2. Aday ayşe   türkmen 27  65
3. Aday fatma  aydin   19  57
4. Aday mehmet keskin  41  80
5. Aday ahmet  aksoy   29  79

In [24]:
#Veri çerçevesindeki bir sütunu adini kullanarak da silebiliriz.
Silinecek_VC_2 = VC_1 
Silinecek_VC_2$isim = NULL

#veri çerçevesinin ilk hali
Silinecek_VC_2

        Ad     Soyad   Boy Yaş Kilo
1. Aday ali    yilmaz  177 25  75
2. Aday ayşe   türkmen 165 27  65
3. Aday fatma  aydin   158 19  57
4. Aday mehmet keskin  190 41  80
5. Aday ahmet  aksoy   184 29  79

In [25]:
#satır silme işleminde de sütunlarda olduðu gibi index kullanılarak silme işlemi gerçekleştirilebilir.
Silinecek_VC_2[-2,] #2. satır siliniyor.

        Ad     Soyad  Boy Yaş Kilo
1. Aday ali    yilmaz 177 25  75
3. Aday fatma  aydin  158 19  57
4. Aday mehmet keskin 190 41  80
5. Aday ahmet  aksoy  184 29  79

# Diziler

In [26]:
degerler=seq(1,60)
Dizi_1=array(degerler,dim=c(3,4,5)) #1. boyut indisi x 2. boyut indisi x 3. boyut indisi
Dizi_1

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

, , 3

     [,1] [,2] [,3] [,4]
[1,]   25   28   31   34
[2,]   26   29   32   35
[3,]   27   30   33   36

, , 4

     [,1] [,2] [,3] [,4]
[1,]   37   40   43   46
[2,]   38   41   44   47
[3,]   39   42   45   48

, , 5

     [,1] [,2] [,3] [,4]
[1,]   49   52   55   58
[2,]   50   53   56   59
[3,]   51   54   57   60

Dilersek dimnames komutu ile de boyutların isimlerini tanımlayabiliriz.

In [27]:
Boyut_1_isimleri = c ("Boyut_1_1","Boyut_1_2","Boyut_1_3")
Boyut_2_isimleri = c ("Boyut_2_1","Boyut_2_2","Boyut_2_3","Boyut_2_4")
Boyut_3_isimleri = c ("Boyut_3_1","Boyut_3_2","Boyut_3_3","Boyut_3_4","Boyut_3_5")
Dizi_1=array(degerler,dim=c(3,4,5),dimnames = list(Boyut_1_isimleri,Boyut_2_isimleri,Boyut_3_isimleri))
Dizi_1

, , Boyut_3_1

          Boyut_2_1 Boyut_2_2 Boyut_2_3 Boyut_2_4
Boyut_1_1         1         4         7        10
Boyut_1_2         2         5         8        11
Boyut_1_3         3         6         9        12

, , Boyut_3_2

          Boyut_2_1 Boyut_2_2 Boyut_2_3 Boyut_2_4
Boyut_1_1        13        16        19        22
Boyut_1_2        14        17        20        23
Boyut_1_3        15        18        21        24

, , Boyut_3_3

          Boyut_2_1 Boyut_2_2 Boyut_2_3 Boyut_2_4
Boyut_1_1        25        28        31        34
Boyut_1_2        26        29        32        35
Boyut_1_3        27        30        33        36

, , Boyut_3_4

          Boyut_2_1 Boyut_2_2 Boyut_2_3 Boyut_2_4
Boyut_1_1        37        40        43        46
Boyut_1_2        38        41        44        47
Boyut_1_3        39        42        45        48

, , Boyut_3_5

          Boyut_2_1 Boyut_2_2 Boyut_2_3 Boyut_2_4
Boyut_1_1        49        52        55        58
Boyut_1_2        50        53        56        59
Boyut_1_3        51        54        57        60

Dört boyutlu bir dizi tanımlamak istersek sadece dim komutu ile tanımladığımız boyut içeriğine 4. bir indis eklememiz gerekir.

In [28]:
degerler2=seq(1,120)
Dizi_2=array(degerler,dim=c(2,3,4,5)) #1. boyut indisi x 2. boyut indisi x 3. boyut indisi x 4. boyut indisi
Dizi_2

, , 1, 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2, 1

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3, 1

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4, 1

     [,1] [,2] [,3]
[1,]   19   21   23
[2,]   20   22   24

, , 1, 2

     [,1] [,2] [,3]
[1,]   25   27   29
[2,]   26   28   30

, , 2, 2

     [,1] [,2] [,3]
[1,]   31   33   35
[2,]   32   34   36

, , 3, 2

     [,1] [,2] [,3]
[1,]   37   39   41
[2,]   38   40   42

, , 4, 2

     [,1] [,2] [,3]
[1,]   43   45   47
[2,]   44   46   48

, , 1, 3

     [,1] [,2] [,3]
[1,]   49   51   53
[2,]   50   52   54

, , 2, 3

     [,1] [,2] [,3]
[1,]   55   57   59
[2,]   56   58   60

, , 3, 3

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 4, 3

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 1, 4

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 2, 4

     [,1] [,2] [,3]
[1,]   19   21   23
[2,]   20   22   24

, , 3, 4

     [,1] [,2] [,3]
[1,]   25   27   29
[2,]   26   28   30

, , 4, 4

     [,1] [,2] [,3]
[1,]   31   33   35
[2,]   32   34   36

, , 1, 5

     [,1] [,2] [,3]
[1,]   37   39   41
[2,]   38   40   42

, , 2, 5

     [,1] [,2] [,3]
[1,]   43   45   47
[2,]   44   46   48

, , 3, 5

     [,1] [,2] [,3]
[1,]   49   51   53
[2,]   50   52   54

, , 4, 5

     [,1] [,2] [,3]
[1,]   55   57   59
[2,]   56   58   60

Dizi elemanlarına erişmek için tıpkı veri çerçevelerinde olduğu gibi indisler kullanırız fakat bu indis sayısı 2’den fazladır.

In [29]:
Dizi_1[2,3,4] #Dizi_1 isimli dizi tipli değişkenin (2,3,4) indizli elemanının değeri

[1] 44

In [30]:
Dizi_2[2,3,1,4] #Dizi_1 isimli dizi tipli değişkenin (2,3,1,4) indizli elemanının değeri

[1] 18

In [31]:
Dizi_1[, , 1]

          Boyut_2_1 Boyut_2_2 Boyut_2_3 Boyut_2_4
Boyut_1_1 1         4         7         10
Boyut_1_2 2         5         8         11
Boyut_1_3 3         6         9         12

In [32]:
Dizi_1[2, ,]

          Boyut_3_1 Boyut_3_2 Boyut_3_3 Boyut_3_4 Boyut_3_5
Boyut_2_1  2        14        26        38        50
Boyut_2_2  5        17        29        41        53
Boyut_2_3  8        20        32        44        56
Boyut_2_4 11        23        35        47        59

In [33]:
Dizi_2[, , 3, 1]

     [,1] [,2] [,3]
[1,] 13   15   17
[2,] 14   16   18

# Dosya İşlemleri

In [ ]:
getwd() # Dizin bilgisi almak için kullanılır...

setwd("C:/R_Giris/") # Aktif dizini değiştirmek için kullanılır.
dir() #Aktif dizindeki dosyaları listeler...

sink("deneme.txt") #Konsola yazılacak olan çıktıları belirtilen dosya içerisine aktarır.